#41 / upload version information
Holo-Host/net-stats-daemon pull request #6
Opened 2022-04-06 19:20 UTC by firestack

HoloPorts currently auto-update from a hydra channel every 10 minutes. This PR makes failures to update more visible by sending the current `holo-nixpkgs` channel version and the version of the `holo-nixpkgs` channel that the `current-system` is built against, introduced in PR [Holo-Host/holo-nixpkgs#1205](https://github.com/Holo-Host/holo-nixpkgs/pull/1205). 

This adds the functions necessary to read the [version information](https://github.com/Holo-Host/holo-nixpkgs/pull/1205) from the system and the `holo-nixpkgs` channel and then send it to [Holo-Host/hp-stats-api](https://github.com/Holo-Host/hp-stats-api).

---

Addresses part of: https://github.com/Holo-Host/bugs-n-issues/issues/41
Depends on: https://github.com/Holo-Host/holo-nixpkgs/pull/1205
Additional Work:

2022-04-11 20:54 UTC, peeech commented on src/stats.rs
> +    val.and_then(|str| str.trim().parse::<bool>().ok())
sweet

2022-04-12 07:51 UTC, peeech commented on src/stats.rs
> +    holoport_version: Option<String>,
```suggestion
    hpos_version: Option<String>,
```
We are internally using word "holoport" for describing hardware, while HPOS is the software

2022-04-12 08:07 UTC, peeech requested changes
All great, just a little request for renaming a member of `pub struct Stats`. Also README needs updating, but I will be happy to do that in a separate PR.

2022-04-12 08:07 UTC, peeech commented on src/stats.rs
> +            holoport_version: get_holo_nixpkgs_version(),
```suggestion
            hpos_version: get_holo_nixpkgs_version(),
```

2022-04-12 10:45 UTC, firestack commented on src/stats.rs
> +            holoport_version: get_holo_nixpkgs_version(),
Thanks! I'll make sure this gets applied on the other side too https://github.com/Holo-Host/hp-stats-api/pull/19

2022-04-12 10:46 UTC, firestack commented on src/stats.rs
> +    holoport_version: Option<String>,
https://github.com/Holo-Host/net-stats-daemon/pull/6#discussion_r848289950

2022-04-12 19:48 UTC, peeech approved these changes
Great :-)

2022-04-12 19:48 UTC, merged